# Generated by Django 5.1.2 on 2024-12-18 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_pledge_athlete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='athlete_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.athleteprofile'),
            preserve_default=False,
        ),
    ]
