# Generated by Django 5.1 on 2024-10-21 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge_supporter_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='project',
        ),
        migrations.AddField(
            model_name='pledge',
            name='is_fulfilled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField(null=True)),
                ('age', models.IntegerField()),
                ('sport', models.CharField(max_length=150)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funds_raised', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_open', models.BooleanField(default=True)),
                ('funding_breakdown', models.TextField(null=True)),
                ('achievements', models.TextField(null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('progress_updates', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_athlete_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='pledge',
            name='athlete_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.athleteprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True)),
                ('supporters', models.ManyToManyField(blank=True, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('athlete_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.athleteprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
