# Generated by Django 5.1.2 on 2024-12-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_pledge_athlete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='date_awarded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
