# Generated by Django 5.1 on 2024-10-21 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_pledge_project_pledge_is_fulfilled_and_more'),
    ]

    operations = [
    ]
