# Generated by Django 5.1 on 2024-09-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_data_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Silly_Dog_%282277051513%29.jpg/320px-Silly_Dog_%282277051513%29.jpg'),
            preserve_default=False,
        ),
    ]
